services:
  - type: web
    name: realtime-chat-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.9.0
      - key: PORT
        value: 10000
    autoDeploy: false
